default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: mercari_umeda
  host: db

development:
  <<: *default
  database: mercari_development

test:
  <<: *default
  database: mercari_test

production:
  <<: *default
  database: mercari_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock
